mutation (
  $input: SystemDevFlagsInput!
) {
  system {
    updateDevFlags(
      input: $input
    ) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
